spring:
  profiles:
    active: dev
  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# mybatis 配置
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml
  # 打开日志 spring-boot-starter 中已包含 slf4j+logback
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.jsoncc.bean #别名 该包下面的文件可以免写包名，小写类名

# 配置日志权限
logging:
  level:
    ROOT: info

server:
  port: 8090
