spring:
  profiles:
    active: dev

# mybatis 配置
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml
  # 打开日志 spring-boot-starter 中已包含 slf4j+logback
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置日志权限
logging:
  level:
    ROOT: off

server:
  port: 8090
